In [ ]:
import numpy as np

In [ ]:
#data matrix for pca
data=np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#mean of each column
M=np.mean(data.T,axis=1)
M

array([3., 4.])

In [ ]:
#subtract the mean from data
scaled_data=data-M
scaled_data

array([[-2., -2.],
       [ 0.,  0.],
       [ 2.,  2.]])

In [ ]:
#covariance Matrixs on scaled data
V=np.cov(scaled_data.T)
V

array([[4., 4.],
       [4., 4.]])

In [ ]:
# eigen values and eigen vectors
values,vectors=np.linalg.eig(V)

In [ ]:
#eigen values which is explained variance of components
values

array([8., 0.])

In [ ]:
#eigen vectors which are principle components
vectors

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [ ]:
vectors.T

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [ ]:
scaled_data.T

array([[-2.,  0.,  2.],
       [-2.,  0.,  2.]])

In [ ]:
#project the data /transform the data 
p=vectors.T.dot(scaled_data.T)

In [ ]:
p.T#project the data /transform the data 
#p=vect

array([[-2.82842712,  0.        ],
       [ 0.        ,  0.        ],
       [ 2.82842712,  0.        ]])

In [ ]:
from sklearn.decomposition import PCA
pca=PCA()
pca.fit(data)

PCA()

In [ ]:
pca.components_

array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

In [ ]:
pca.explained_variance_

array([8.00000000e+00, 2.25080839e-33])

In [ ]:
p=pca.transform(data)
p

array([[-2.82842712e+00,  2.22044605e-16],
       [ 0.00000000e+00,  0.00000000e+00],
       [ 2.82842712e+00, -2.22044605e-16]])