# Import Statement

In [1]:
#Tanveer kadun ghene

# Import Packages and Library

# Numpy 

In [2]:
import numpy as np

In [3]:
a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [4]:
b=np.array([[1,2,3],[3,4,5],[6,7,8]])
print(b)

[[1 2 3]
 [3 4 5]
 [6 7 8]]


In [5]:
#properties

print(a.size)
print(a.shape)
print(a.dtype)
print(a.ndim)
print(type(a))

4
(2, 2)
int32
2
<class 'numpy.ndarray'>


In [6]:
a=np.ones((5,5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
b=np.zeros((5,4))
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
c=np.full((5,4),7)
print(c)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [9]:
#Random values 


a=np.random.random((3,5))
print(a)

[[0.31754284 0.7194439  0.84691906 0.25018154 0.3294829 ]
 [0.6643728  0.01300804 0.99725828 0.91880107 0.79024308]
 [0.18378193 0.12976637 0.33383431 0.50545112 0.22921007]]


In [10]:
b=np.random.randint(1,50,(3,4))
print(b)

[[29 13 16 42]
 [24 47 32 27]
 [ 6 15 25 22]]


In [11]:
#arange

a=np.arange(0,20,5)
print(a)
print(a.shape)

[ 0  5 10 15]
(4,)


In [12]:
#linspace

b=np.linspace(1,20,10)
print(b)

[ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ]


In [13]:
a=np.array([1,2,3,4,5,6])
#print(a)

a=a.reshape(1,-1)
print(a)

[[1 2 3 4 5 6]]


In [14]:
a=np.array([1,2,3,4,5,6])
#print(a)
a=a.reshape(-1,1)
print(a)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [15]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

flat=a.flatten()
print(flat)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [16]:
a=np.array([[1,2],[3,4]])
print(a)

print(a+1)
print(a-3)
print(a*2)
print(a/2)

print(np.sin(a))
print(np.cos(a))
print(np.tan(a))
print(np.sqrt(a))
print(np.exp(a))

[[1 2]
 [3 4]]
[[2 3]
 [4 5]]
[[-2 -1]
 [ 0  1]]
[[2 4]
 [6 8]]
[[0.5 1. ]
 [1.5 2. ]]
[[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]]
[[ 0.54030231 -0.41614684]
 [-0.9899925  -0.65364362]]
[[ 1.55740772 -2.18503986]
 [-0.14254654  1.15782128]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]


In [17]:
#transpose

print(a.T)

[[1 3]
 [2 4]]


In [18]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

print(np.matmul(a,b)) #matrix multiplication
print(np.dot(a,b)) #matrix multiplication 
print(np.sum(a)) # matrix addition of each element
print(np.min(a)) # 
print(np.max(a)) # maximum 

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
10
1
4


In [19]:
#for column 

print(np.max(a,axis=0))
print(np.min(a,axis=0))

#for row 

print(np.max(a,axis=1))
print(np.min(a,axis=1))

[3 4]
[1 2]
[2 4]
[1 3]


In [20]:
#sort

a=np.array([[6,2],[2,0]])
print(np.sort(a))

print(np.sort(a,axis=0))

[[2 6]
 [0 2]]
[[2 0]
 [6 2]]


In [21]:
#slice

a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)


print(a[1:2,1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[5 6]]


In [22]:
print(a[0,:1])
print(a[0,2:])
print(a[2,:1])
print(a[2,2:])
#
#print(a[0,:1], a[0,2:],a[2,:1], a[2,2:])
print(a[::2,::2])

[1]
[3]
[7]
[9]
[[1 3]
 [7 9]]


In [23]:
print(a[1:2,1:2])

#or
print(a[1,1])

[[5]]
5


In [24]:
print(a[::2,::])

[[1 2 3]
 [7 8 9]]


In [25]:
#create a 5*2 integer array from a range between 100 to 200 such that the difference between each element is 10
#ans
a=np.arange(100,200,10)
print(a)
print(a.reshape(5,2))

[100 110 120 130 140 150 160 170 180 190]
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [26]:
a=np.array([[3,6,9,12],[15,18,21,24],[27,30,33,36],[39,42,45,48],[51,54,57,60]])
print(a)

# aquestion bove is the given numpy array return array of add rows and even columns

print(a[::2,1::2])

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]
[[ 6 12]
 [30 36]
 [54 60]]


# Pandas

#3 types of data 
1. Series 1D
2. Data Frame 2D
3. Panel 3D/4D

In [27]:
#create data with dictionary

d={"roll":[1,2,3,4,5],"name":["a","b","c","d","e"],"marks":[11,13,12,15,12]}

In [28]:
import pandas as pd 
df=pd.DataFrame(d)
print(df)

   roll name  marks
0     1    a     11
1     2    b     13
2     3    c     12
3     4    d     15
4     5    e     12


In [29]:
print(df[["roll","name"]])
print(df["roll"])
print(type(df["roll"]))
print(df.roll)
print(df.roll,df.name)

   roll name
0     1    a
1     2    b
2     3    c
3     4    d
4     5    e
0    1
1    2
2    3
3    4
4    5
Name: roll, dtype: int64
<class 'pandas.core.series.Series'>
0    1
1    2
2    3
3    4
4    5
Name: roll, dtype: int64
0    1
1    2
2    3
3    4
4    5
Name: roll, dtype: int64 0    a
1    b
2    c
3    d
4    e
Name: name, dtype: object


In [30]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
roll     5 non-null int64
name     5 non-null object
marks    5 non-null int64
dtypes: int64(2), object(1)
memory usage: 200.0+ bytes
None


In [31]:
print(df.mean())
print(df.max())
print(df.min())
print(df.median())
print(df.count())
print(df.mode())
print(df.sum())
print(df.describe())

roll      3.0
marks    12.6
dtype: float64
roll      5
name      e
marks    15
dtype: object
roll      1
name      a
marks    11
dtype: object
roll      3.0
marks    12.0
dtype: float64
roll     5
name     5
marks    5
dtype: int64
   roll name  marks
0     1    a   12.0
1     2    b    NaN
2     3    c    NaN
3     4    d    NaN
4     5    e    NaN
roll        15
name     abcde
marks       63
dtype: object
           roll      marks
count  5.000000   5.000000
mean   3.000000  12.600000
std    1.581139   1.516575
min    1.000000  11.000000
25%    2.000000  12.000000
50%    3.000000  12.000000
75%    4.000000  13.000000
max    5.000000  15.000000


In [32]:
#iloc

print(df.iloc[1,1])
print(df.iloc[[1,3],:])
print(df.iloc[[2,4],[1,2]])
print(df.iloc[::2,1::2])

b
   roll name  marks
1     2    b     13
3     4    d     15
  name  marks
2    c     12
4    e     12
  name
0    a
2    c
4    e


In [33]:
#loc

print(df.loc[1,"name"])
print(df.loc[[1,3],["roll","name"]])
print(df.loc[1::2,["name"]])

b
   roll name
1     2    b
3     4    d
  name
1    b
3    d
