In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
d={"x":[1,2,3,3,4,4,5,6],"y":[1.5,3.5,1.5,5,2,5,5,3],"label":[0,0,0,0,1,1,1,1]}
df=pd.DataFrame(d)
df

x    y  label
0  1  1.5      0
1  2  3.5      0
2  3  1.5      0
3  3  5.0      0
4  4  2.0      1
5  4  5.0      1
6  5  5.0      1
7  6  3.0      1

In [3]:
plt.scatter(df.x, df.y, c=df.label)
plt.scatter([3],[3.5])

In [4]:
x = df[["x","y"]]
y = df["label"]

In [5]:
from sklearn.neighbors import KNeighborsClassifier

In [6]:
model = KNeighborsClassifier(n_neighbors = 3)
model.fit(x,y)

KNeighborsClassifier(n_neighbors=3)

In [7]:
y_pred = model.predict([[3,3.5]])
y_pred

array([0])

#### Another Point

In [8]:
plt.scatter(df.x, df.y, c=df.label)
plt.scatter([4],[3.5])

In [9]:
x = df[["x","y"]]
y = df["label"]

In [10]:
model = KNeighborsClassifier(n_neighbors = 3)
model.fit(x,y)

KNeighborsClassifier(n_neighbors=3)

In [11]:
y_pred = model.predict([[4,3.5]])
y_pred

array([1])

#### practice

In [12]:
d={"x":[1,2,3,3,4,4,5,6],"y":[1.5,3.5,1.5,5,2,5,5,3],"label":[0,1,0,1,0,1,0,1]}
df=pd.DataFrame(d)
df

x    y  label
0  1  1.5      0
1  2  3.5      1
2  3  1.5      0
3  3  5.0      1
4  4  2.0      0
5  4  5.0      1
6  5  5.0      0
7  6  3.0      1

In [13]:
plt.scatter(df.x, df.y, c=df.label)
plt.scatter([4],[3.5])

In [14]:
x = df[["x","y"]]
y = df["label"]

In [15]:
model = KNeighborsClassifier(n_neighbors = 3)
model.fit(x,y)

KNeighborsClassifier(n_neighbors=3)

In [16]:
y_pred = model.predict([[4,3.5]])
y_pred

array([1])

### AD_Purchase Dataset

In [17]:
data = pd.read_csv("AD_purchace.csv")
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [18]:
data["Gender"] = data["Gender"].map({"Male":0,"Female":1})
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510       0   19            19000          0
1  15810944       0   35            20000          0
2  15668575       1   26            43000          0
3  15603246       1   27            57000          0
4  15804002       0   19            76000          0

In [19]:
data.isna().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [20]:
x = data.drop(columns = ["User ID","Purchased"])

In [21]:
y = data["Purchased"]

In [22]:
# Train Test Dataset 

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)

In [23]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors = 3)
model.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [24]:
y_pred = model.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1])

In [25]:
# accuracy

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

acc = accuracy_score(y_test, y_pred)
print(acc)

0.7875


In [26]:
# confusion matrix 

cm = confusion_matrix(y_test, y_pred)
print(cm)

[[48 10]
 [ 7 15]]


In [27]:
# classification report 

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.87      0.83      0.85        58
           1       0.60      0.68      0.64        22

    accuracy                           0.79        80
   macro avg       0.74      0.75      0.74        80
weighted avg       0.80      0.79      0.79        80



In [28]:
# model with Standard Scale 

from sklearn.preprocessing import StandardScaler 

ss = StandardScaler()

scale_x = ss.fit_transform(x)

In [29]:
x_train, x_test, y_train, y_test = train_test_split(scale_x, y, test_size = 0.2, random_state = 1)

In [30]:
model = KNeighborsClassifier(n_neighbors = 3)
model.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [31]:
y_pred = model.predict(x_test)
y_pred

array([0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0])

In [32]:
acc = accuracy_score(y_test, y_pred)
print(acc)

0.85


In [33]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[39  9]
 [ 3 29]]


##### Scaling on x_train, x_test

In [34]:
# model with Standard Scale 
from sklearn.preprocessing import StandardScaler 
ss = StandardScaler()
scale_x_train = ss.fit_transform(x_train)

# model with Standard Scale 

from sklearn.preprocessing import StandardScaler 

ss = StandardScaler()

scale_x_test = ss.fit_transform(x_test)

In [35]:
model.fit(scale_x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [36]:
y_pred = model.predict(scale_x_test)
y_pred

array([0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0])

In [37]:
acc = accuracy_score(y_test, y_pred)
print(acc)

0.8625


In [38]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[42  6]
 [ 5 27]]


In [39]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.89      0.88      0.88        48
           1       0.82      0.84      0.83        32

    accuracy                           0.86        80
   macro avg       0.86      0.86      0.86        80
weighted avg       0.86      0.86      0.86        80



### Iris Dataset

In [40]:
df = pd.read_csv("iris.csv")
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [41]:
df["species"].unique ()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [42]:
df["species"] = df["species"].map({"setosa":0,"versicolor":1,"virginica":2})
df.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [43]:
x = df.drop(columns = ["species"])
y = df["species"]

In [44]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [45]:
model = KNeighborsClassifier(n_neighbors = 3)
model.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [46]:
y_pred = model.predict(x_test)
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 2, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0])

In [47]:
print(accuracy_score(y_test, y_pred))

0.9666666666666667


In [48]:
# and now after scalling the data

In [49]:
# model with Standard Scale 
from sklearn.preprocessing import StandardScaler 
ss = StandardScaler()
scale_x_train = ss.fit_transform(x_train)
# model with Standard Scale 
from sklearn.preprocessing import StandardScaler 
ss = StandardScaler()
scale_x_test = ss.fit_transform(x_test)

In [50]:
model.fit(scale_x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [51]:
y_pred = model.predict(scale_x_test)
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 2, 1, 2, 1, 1, 2, 2, 0, 2, 1, 0, 0, 2, 2,
       0, 0, 2, 0, 0, 1, 1, 0])

In [52]:
print(accuracy_score(y_test, y_pred))

0.8333333333333334


After scaling accuracy is not improved (Iris Dataset)

## Hyper Parameter Tuning KNN

In [53]:
model = KNeighborsClassifier()

In [54]:
n_neighbors = range(1,31)
metric = ["euclidean","manhattan","minkowski"]
weights = ["uniform","distance"]
grid = {"n_neighbors":n_neighbors, "metric":metric, "weights":weights}


In [55]:
# cv 
from sklearn.model_selection import RepeatedStratifiedKFold 
kfold = RepeatedStratifiedKFold(n_splits = 5, n_repeats = 3, random_state = 1)



In [56]:
# Grid Search cv 
from sklearn.model_selection import GridSearchCV 
grid_cv = GridSearchCV(estimator = model, param_grid = grid, cv = kfold, scoring = "accuracy", n_jobs = 1)


In [57]:
# result 

res = grid_cv.fit(x_train, y_train)

In [58]:
res.best_params_

{'metric': 'euclidean', 'n_neighbors': 8, 'weights': 'uniform'}

In [59]:
res.best_score_

0.9638888888888889

In [60]:
# best_params_ output here 

from sklearn.neighbors import KNeighborsClassifier
model_best = KNeighborsClassifier(metric = "manhattan", n_neighbors = 11, weights = "uniform")
model_best(x_train, y_train)

TypeError: 'KNeighborsClassifier' object is not callable

In [ ]:
y_pred_best = model_best.predict(x_test)
y_pred_best

In [ ]:
print(accuracy_score(y_test, y_pred_best))