In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("diabetes.csv")
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [4]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [5]:
#sns.catplot(data = df, x=Outcome)

In [6]:
x = df.drop(columns = ["Outcome"])
y = df["Outcome"]

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [9]:
from sklearn.svm import SVC

In [10]:
model = SVC()

In [11]:
model.fit(x_train, y_train)

SVC()

In [12]:
y_pred = model.predict(x_test)
y_pred

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [14]:
print("Accuracy is : ", accuracy_score(y_test, y_pred))

Accuracy is :  0.7922077922077922


In [15]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[98,  9],
       [23, 24]])

In [16]:
sns.heatmap(cm, annot = True)

In [17]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.81      0.92      0.86       107
           1       0.73      0.51      0.60        47

    accuracy                           0.79       154
   macro avg       0.77      0.71      0.73       154
weighted avg       0.78      0.79      0.78       154



In [18]:
# Now Kernel "Poly" & C = 10

from sklearn.svm import SVC 

model = SVC(kernel = "poly", C = 10)

model.fit(x_train, y_train)

y_pred = model.predict(x_test)

print("Accuracy is : ", accuracy_score(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)

sns.heatmap(cm, annot = True)

print(classification_report(y_test, y_pred))

Accuracy is :  0.8246753246753247
              precision    recall  f1-score   support

           0       0.84      0.93      0.88       107
           1       0.78      0.60      0.67        47

    accuracy                           0.82       154
   macro avg       0.81      0.76      0.78       154
weighted avg       0.82      0.82      0.82       154



In [19]:
# Now Kernel "rbf" & C = 15

from sklearn.svm import SVC 

model = SVC(kernel = "rbf", C = 15)

model.fit(x_train, y_train)

y_pred = model.predict(x_test)

print("Accuracy is : ", accuracy_score(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)

sns.heatmap(cm, annot = True)

print(classification_report(y_test, y_pred)) 

Accuracy is :  0.8116883116883117
              precision    recall  f1-score   support

           0       0.84      0.91      0.87       107
           1       0.74      0.60      0.66        47

    accuracy                           0.81       154
   macro avg       0.79      0.75      0.76       154
weighted avg       0.81      0.81      0.81       154



In [20]:
# Now Kernel "linear" & C = 10
from sklearn.svm import SVC 
model = SVC(kernel = "linear", C = 15)
model.fit(x_train, y_train)
y_pred = model.predict(x_test)
print("Accuracy is : ", accuracy_score(y_test, y_pred))
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot = True)
print(classification_report(y_test, y_pred)) 

Accuracy is :  0.7922077922077922
              precision    recall  f1-score   support

           0       0.83      0.88      0.85       107
           1       0.68      0.60      0.64        47

    accuracy                           0.79       154
   macro avg       0.76      0.74      0.75       154
weighted avg       0.79      0.79      0.79       154



In [21]:
# Now Kernel "sigmoid" & C = 15

from sklearn.svm import SVC 

model = SVC(kernel = "sigmoid", C = 100)

model.fit(x_train, y_train)

y_pred = model.predict(x_test)

print("Accuracy is : ", accuracy_score(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)

sns.heatmap(cm, annot = True)

print(classification_report(y_test, y_pred)) 

Accuracy is :  0.44805194805194803
              precision    recall  f1-score   support

           0       0.62      0.53      0.57       107
           1       0.19      0.26      0.22        47

    accuracy                           0.45       154
   macro avg       0.41      0.39      0.40       154
weighted avg       0.49      0.45      0.47       154



In [22]:
# Now Kernel "precomputed" & C = 15

#from sklearn.svm import SVC 

#model = SVC(kernel = "precomputed", C = 15)

#model.fit(x_train, y_train)

#y_pred = model.predict(x_test)

#print("Accuracy is : ", accuracy_score(y_test, y_pred))

#cm = confusion_matrix(y_test, y_pred)

#sns.heatmap(cm, annot = True)

#print(classification_report(y_test, y_pred)) 

### Hyper Parameter Tuning

In [23]:
#estimator 
model = SVC()

#parameter 
kernel = ["linear", "poly", "rbf", "sigmoid"]
C = [50, 10, 1]
grid = {"kernel":kernel, "C":C}

# cv
from sklearn.model_selection import RepeatedStratifiedKFold 
cv = RepeatedStratifiedKFold(n_splits = 5, n_repeats = 3, random_state = 1)

# Grid Search CV 
from sklearn.model_selection import GridSearchCV 
grid_cv = GridSearchCV(estimator = model, param_grid = grid, cv = cv, n_jobs = 1)
#.   

In [24]:
#res = grid_cv.fit(x_train, y_train)

In [25]:
#res.best_params_

In [26]:
#res.best_score_

# Credit Card Data

In [27]:
data = pd.read_csv("creditcard.csv")
data.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [28]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     28

In [29]:
data.isna().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [30]:
data.shape

(284807, 31)

In [31]:
data["Class"].unique()

array([0, 1])

In [32]:
data["Class"].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [33]:
sns.catplot(data = data, x = "Class", kind = 'count')

In [34]:
data = data.drop(columns = ["Time"])

In [35]:
from sklearn.preprocessing import StandardScaler

In [37]:
ss = StandardScaler()

data["Amount"] = ss.fit_transform(data[["Amount"]])

In [38]:
x = data.drop(columns = ["Class"])
y = data["Class"]

In [39]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [40]:
from sklearn.linear_model import LogisticRegression 
model = LogisticRegression()

model.fit(x_train, y_train)

y_pred = model.predict(x_test)

In [41]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [42]:
print("Accuracy is : ", accuracy_score(y_test, y_pred))

Accuracy is :  0.9991924440855307


In [43]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
sns.heatmap(cm, annot = True)

[[56852     9]
 [   37    64]]


In [45]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56861
           1       0.88      0.63      0.74       101

    accuracy                           1.00     56962
   macro avg       0.94      0.82      0.87     56962
weighted avg       1.00      1.00      1.00     56962



## Sampling Techniques

1. Over Sampling : Opposite of Under Sampling
2. Under Sampling :- 0 is Majority = 1000 & 1 is Minarity = 100 -> Convert 1000 class in 100 class

In [46]:
# Under Sampling of Data 
# 0 -> Non Fraud
# 1 -> Fraud 

no_fraud = data[data["Class"] == 0].index
fraud = data[data["Class"] == 1].index

random_index = np.random.choice(no_fraud, len(fraud), replace = False)
len(random_index)

undersample_index = np.concatenate([fraud, random_index])
len(undersample_index)

undersample = data.iloc[undersample_index,:]

In [47]:
x = undersample.drop(columns = ["Class"])
y = undersample["Class"]

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

from sklearn.linear_model import LogisticRegression 
model = LogisticRegression()
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print("Accuracy is : ", accuracy_score(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)
print(cm)
sns.heatmap(cm, annot = True)

print(classification_report(y_test, y_pred))

Accuracy is :  0.9543147208121827
[[102   4]
 [  5  86]]
              precision    recall  f1-score   support

           0       0.95      0.96      0.96       106
           1       0.96      0.95      0.95        91

    accuracy                           0.95       197
   macro avg       0.95      0.95      0.95       197
weighted avg       0.95      0.95      0.95       197



In [48]:
# Over Sampling of Data 
# 0 -> Non Fraud
# 1 -> Fraud 
no_fraud = data[data["Class"] == 0].index
fraud = data[data["Class"] == 1].index

# Random_index for fraud with mejority class 
random_index = np.array(np.random.choice(fraud, len(no_fraud), replace = True))

oversample_index = np.concatenate([no_fraud, random_index])

oversample = data.iloc[oversample_index,:]

In [49]:
x = undersample.drop(columns = ["Class"])
y = undersample["Class"]

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

from sklearn.linear_model import LogisticRegression 
model = LogisticRegression()
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
print("Accuracy is : ", accuracy_score(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)
print(cm)
sns.heatmap(cm, annot = True)

print(classification_report(y_test, y_pred))

Accuracy is :  0.9543147208121827
[[102   4]
 [  5  86]]
              precision    recall  f1-score   support

           0       0.95      0.96      0.96       106
           1       0.96      0.95      0.95        91

    accuracy                           0.95       197
   macro avg       0.95      0.95      0.95       197
weighted avg       0.95      0.95      0.95       197

