In [2]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("iris.csv")
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df["species"].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [6]:
df["species"].value_counts()

versicolor    50
virginica     50
setosa        50
Name: species, dtype: int64

In [7]:
df["species"] = df["species"].map({"setosa":0,"versicolor":1,"virginica":2})
df.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [8]:
x = df.drop(columns = ["species"])
y = df["species"]

In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)

In [10]:
from sklearn.neighbors import KNeighborsClassifier 
model = KNeighborsClassifier()

In [11]:
model.fit(x_train, y_train)

KNeighborsClassifier()

In [12]:
y_pred = model.predict(x_test)

In [13]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [14]:
print("Accuracy is : ", accuracy_score(y_test, y_pred))

Accuracy is :  0.9666666666666667


In [15]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
sns.heatmap(cm, annot = True)
plt.show()

[[11  0  0]
 [ 0 12  1]
 [ 0  0  6]]


In [16]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.92      0.96        13
           2       0.86      1.00      0.92         6

    accuracy                           0.97        30
   macro avg       0.95      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30



In [17]:
# now we can check accuracy after scaling

In [18]:
# model with Standard Scale 
from sklearn.preprocessing import StandardScaler 
ss = StandardScaler()
scale_x_train = ss.fit_transform(x_train)

# model with Standard Scale 
from sklearn.preprocessing import StandardScaler 
ss = StandardScaler()
scale_x_test = ss.fit_transform(x_test)

In [19]:
model.fit(scale_x_train, y_train)

KNeighborsClassifier()

In [22]:
y_pred = model.predict(scale_x_test)

In [23]:
print("Accuracy is : ", accuracy_score(y_test, y_pred))

Accuracy is :  0.8666666666666667


In [24]:
# After scaling accuracy is Decreased